export const FORBIDDEN = [
  'шанс одобрения',
  'вероятность визы',
  'гарантия визы',
  'гарантирован',
  'AI решил',
  'ИИ решил',
  'точно получите визу',
  '100% одобрен',
  'решено',
  'validated',
  'verified by consulate',
  'real-time alerts',
  'realtime alerts',
  'обновлено сегодня',
  'источник консульства',
  'движок',
  'engine',
  'rule engine',
  'RDC v1',
  'confidence breakdown',
  'confidence score',
  'ruleset',
  'policy engine',
  'decision engine',
  'inference',
  'model output',
  'expert verified',
] as const
