#!/bin/zsh
set -euo pipefail

STREAM_NAME="Stream 3 - AI Integrations / Infra / Audit"
WORKTREE="$HOME/Projects/active-holidays-stream3-ai-infra-audit"
EXPECTED_BRANCH="feat/stream3-ai-infra-audit"

die() {
  echo ""
  echo "BLOCKED: $1"
  echo ""
  read "reply?Press Enter to close..."
  exit 1
}

echo "Launching $STREAM_NAME"
echo "Worktree: $WORKTREE"
echo "Expected branch: $EXPECTED_BRANCH"

[[ -d "$WORKTREE" ]] || die "Worktree does not exist: $WORKTREE"
cd "$WORKTREE"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "Not a git worktree: $WORKTREE"

CURRENT_BRANCH="$(git branch --show-current)"
[[ "$CURRENT_BRANCH" == "$EXPECTED_BRANCH" ]] || die "Expected branch '$EXPECTED_BRANCH', got '$CURRENT_BRANCH'"

DIRTY_BLOCKERS="$(git status --short --untracked-files=all | awk '
{
  path = substr($0, 4)
  if (path !~ /^\.codex\/notes\// && path !~ /^\.codex\/local\// && path !~ /^\.codex\/.*\.local\./) print
}')"
[[ -z "$DIRTY_BLOCKERS" ]] || die "Dirty worktree outside local .codex notes:\n$DIRTY_BLOCKERS"

[[ -f "AGENTS.md" ]] || die "Missing AGENTS.md"
[[ -f "docs/workflows/parallel-codex-streams.md" ]] || die "Missing docs/workflows/parallel-codex-streams.md"
[[ -f "docs/ui/premium-scorecard.md" ]] || die "Missing docs/ui/premium-scorecard.md"

PROMPT_FILE="$(mktemp -t ah-stream3-ai-infra-audit.XXXXXX.md)"
trap 'rm -f "$PROMPT_FILE"' EXIT

cat > "$PROMPT_FILE" <<'PROMPT'
You are running Stream 3 from the one-touch Codex launcher.

STREAM
- Name: AI Integrations / Infra / Audit
- Worktree: ~/Projects/active-holidays-stream3-ai-infra-audit
- Branch: feat/stream3-ai-infra-audit
- Complexity: 8/10

GLOBAL CONTEXT
- PR #40 merged: Premium UI Gate / governance.
- PR #41 merged: permanent 3-stream Codex model.
- PR #42 exists for project handoff ledger. Do not touch PR #42 unless explicitly required.
- User only transfers prompts/results. Codex performs repo actions.
- One stream = one branch/worktree.
- No standalone task below 6/10.
- Engine decides. AI explains. UI shows provenance.
- AI must not own deterministic truth.

SKILL SET
- Primary mode: review-gate with ai-recommendation-boundary lens.
- Core: ah-control-protocol, ah-ai-trust-layer, ah-backend-contracts, ah-review-release, bank-grade-review, codex-security:threat-model, codex-security:attack-path-analysis, codex-security:finding-discovery, phase-gate-sync, product-os-audit.
- Accelerators: openai-developers:agents-sdk for AI contract/eval framing; vercel:observability for traces/logs/stale proof; vercel:investigation-mode for debug order; vercel:verification for end-to-end proof; product-ui-ux-ai-master-reviewer for trust-copy blockers; superpowers:systematic-debugging only for concrete failures.
- Finish: ah-review-release, superpowers:verification-before-completion, vercel:verification.

HARD STOPS
- Stop if this worktree is dirty except local-only .codex notes.
- Stop if branch is not feat/stream3-ai-infra-audit.
- Stop if task requires package/lockfile/dependency/CI/schema changes.
- Stop if scope crosses into Stream 1 or Stream 2 without explicit note.
- Stop if broad business or broad UI implementation is required.
- Stop before changing deterministic contracts without Stream 1 coordination.
- Stop before changing UI copy without Stream 2 coordination unless it is a critical truth-safety fix.

GLOBAL CHECKS
Run first:
- Read AGENTS.md.
- Read docs/workflows/parallel-codex-streams.md.
- Read docs/ui/premium-scorecard.md.
- git branch --show-current
- git status --short --branch
- git diff --check
- git diff --stat
- Inspect package.json, app/, src/, lib/, API/server/action files.
- Inspect upload/document-related files.
- Inspect AI-related files/prompts if present.
- Inspect existing env/config/security patterns.
- Inspect tests if present.
- Run relevant package scripts only if they already exist.

TASK
Audit AI/truth-safety/integration boundaries and produce blockers for Stream 1 and Stream 2.

GOAL
Produce a concrete audit and blocker map for AI, document handling, provenance, stale guards, forbidden claims, security, observability, and cross-stream risks.

DELIVERABLES
1. Deterministic vs AI ownership map:
   - What engine/server owns.
   - What AI may explain.
   - What UI may display.
   - What must never be AI-owned.

2. Forbidden claims audit:
   Check for:
   - fake readiness
   - fake verification
   - guaranteed visa/result claims
   - "AI approved" language
   - unsupported confidence scores
   - deterministic legal/product claims generated by AI

3. Provenance/source map:
   - What needs source/evidence chips.
   - What needs stale guard.
   - What needs last-updated timestamp.
   - What must be marked unknown/unverified.

4. Upload/document pipeline readiness:
   - current upload/document parsing/classification state
   - missing security checks
   - file type/size risks
   - PII handling risks
   - extraction confidence boundaries
   - human review handoff requirements

5. Stream blockers:
   - blockers for Stream 1
   - blockers for Stream 2
   - severity: P0/P1/P2
   - exact file/area references where possible
   - recommended fix owner

ALLOWED SCOPE
- audit docs
- issue/blocker report
- small safe guards only if obvious and isolated
- no silent broad implementation
- no unrelated refactor

FORBIDDEN SCOPE
- broad business implementation
- broad UI implementation
- package/dependency/lockfile changes
- CI/scripts/schema changes
- changing deterministic contracts without Stream 1 coordination
- changing UI copy without Stream 2 coordination unless it is a critical truth-safety fix

ACCEPTANCE CRITERIA
- Stream 1 gets clear backend/truth blockers.
- Stream 2 gets clear UI/trust-copy blockers.
- AI boundary is explicit.
- Upload/document risks are explicit.
- Audit can be used immediately for PR review.

FINAL REPORT
Must include:
- READY / BLOCKED / NEEDS REWORK
- summary
- files changed
- commands run + exact results
- P0/P1/P2 blocker list
- deterministic vs AI boundary map
- upload/document readiness result
- security/observability risks
- next Stream 3 task
- handoff notes for Stream 1 and Stream 2
- rollback path
PROMPT

codex --cd "$WORKTREE" --sandbox workspace-write --ask-for-approval never "$(cat "$PROMPT_FILE")"
